---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-wordpress
provisioner: nfs.csi.k8s.io
parameters:
  server: configmap://nfs-server-config/NFS_SERVER_IP
  share: /mnt/wordpress
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-wordpress
spec:
  storageClassName: nfs-csi-wordpress
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-mysql
provisioner: nfs.csi.k8s.io
parameters:
  server: configmap://nfs-server-config/NFS_SERVER_IP
  share: /mnt/mysql
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-mysql
spec:
  storageClassName: nfs-csi-mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi