apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  # No namespace, PVs are global
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  nfs:
    path: /
    server: configmap://nfs-server-config/NFS_SERVER_IP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: nfs-pv
