apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
    - hosts:
        - proyecto2.temporaladventures.tech
      secretName: proyecto2-temporaladventures-tech-tls
  rules:
    - host: proyecto2.temporaladventures.tech
      http:
        paths:
          - backend:
              service:
                name: wordpress
                port:
                  number: 80
            path: /
            pathType: Prefix
